Revert "Adding temporary classes to resolve NoSuchMethodError for SAML2Configuration.setCertificateNameToAppend"
This reverts commit 5e3c844f1fdbbdc34695f466b09a9bdad38c960b.