Revert "Adding temporary classes to resolve NoSuchMethodError for BasicSignatureSigningConfiguration.setSigningCredentials"
This reverts commit 6abf7e0abf264be11fbc6a8fa1917ced979f2fa8.